[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

[dev]
  command = "npm install && npm run dev"
  functions = "netlify/functions"
  targetPort = 8888
  port = 8888
