services:
  - type: pserv
    name: anatomie-labs-db
    databaseName: anatomie_labs
    databaseUser: anatomie_user

  - type: web
    name: anatomie-labs-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: anatomie-labs-db
          property: connectionString
      - key: JWT_EXPIRE_TIME
        value: 7d
